services:
  postgres:
    container_name: bragboard-postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=bragboard
      - POSTGRES_USER=bragboard_user
      - POSTGRES_PASSWORD=securepassword
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  api:
    container_name: bragboard-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"       # Web UI / API
      - "37020:37020/udp" # Discovery
      - "37021:37021/udp" # Game State
    environment:
      - DATABASE_HOST=bragboard-postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=bragboard
      - DATABASE_USER=bragboard_user
      - DATABASE_PASSWORD=securepassword
    extra_hosts:
      - "host.docker.internal:host-gateway" # allows access to LAN
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
