name: Build Frontend

on:
    workflow_call:
        inputs:
            node-version:
                description: 'Node.js version to use'
                required: false
                default: '16'

jobs:
    build-frontend:
        runs-on: ubuntu-latest

        steps:
              - name: Checkout code
                uses: actions/checkout@v3

              - name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                  node-version: ${{ inputs.node-version }}

              - name: Install dependencies
                run: |
                  cd frontend
                  npm install

              - name: Build Svelte app
                run: |
                  cd frontend
                  npm run build
                  mkdir -p backend/build
                  mv build/* backend/build/

              - name: Upload build artifacts
                uses: actions/upload-artifact@v3
                with:
                  name: frontend-build
                  path: frontend/backend/build
